<?php
DEFINE('RegTable', 'registertable');
DEFINE('admintable', 'admintable');
DEFINE('EmailValidation', 'emailvalidation');
DEFINE('forgotPass', 'forgottenpass');
DEFINE('Shares', 'Shares');
DEFINE('depositTable', 'deposittable');
DEFINE('kyc', 'kyc');
DEFINE('wallet', 'wallet');
DEFINE('register_bitcoin', 'register_bitcoin');
DEFINE('transaction_bitcoin', 'transaction_bitcoin');
DEFINE('ProfitTable', 'profittable');
DEFINE('referralTable', 'referraltable');
DEFINE('messagenoti', 'messagenoti');
DEFINE('usersPlan', 'plantable');
DEFINE('cryptwithdrawalTable', 'cryptwithdrawaltable');
DEFINE('bnkwithdrawalTable', 'bnkwithdrawaltable');
DEFINE('verificationcode', 'verificationcode');
DEFINE('swap', 'swap');
DEFINE('trade', 'trade');
DEFINE('copytrade', 'copytrade');
DEFINE('thecopytraders', 'thecopytraders');
DEFINE('uploadproof', 'uploadproof');
// DEFINE('sitelink', '//localhost/myProject/');
// DEFINE('sitelink', 'http://172.20.10.6/myProject/');
// DEFINE('sitelink', 'https://swiftmarketsphere.org/');
DEFINE('sitelink', 'http://172.20.10.6:3000/');
DEFINE('apiLink', 'https://api.crownexchange.org/');
DEFINE('appLink', 'https://app.crownexchange.org/');
DEFINE('siteurl', 'https://crownexchange.org/');
DEFINE('siteaddress', '7JR7+F94, George Town, Cayman Islands');
DEFINE('sitenumber', '1(652)59444448');
DEFINE('sitename', 'Crown Exchange');
DEFINE('sitemail', 'support@crownexchange.org');
DEFINE('MAILHOST', 'mail.crownexchange.org');
DEFINE('MAILUSER', 'mail@crownexchange.org');
DEFINE('MAILPASS', 'Z=GhO~2rT9.}');